spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb+srv://dilipchoudhary727:Dilip17@mydatabases.nlny5ch.mongodb.net/?retryWrites=true&w=majority&appName=ai_db
      database: ai_db

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
