spring:
  application:
    name: activity-service

  kafka:
    topic:
      name: activity-event
    bootstrap-server: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    mongodb:
      uri: mongodb+srv://dilipchoudhary727:Dilip17@mydatabases.nlny5ch.mongodb.net/?retryWrites=true&w=majority&appName=activities_db
      database: activities_db

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
